'use client';

import { motion } from 'framer-motion';
import Image from 'next/image';

export function FeaturesGrid() {
  const features = [
    {
      id: 1,
      title: "AI that guides your interview, real-time",
      description: "IntervuAI uses the screen, transcript, and AI to answer questions and suggest follow-ups for you, live.",
      backgroundColor: "bg-blue-500/20 backdrop-blur-xl",
      imagePlaceholder: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=600&h=400&fit=crop&q=80",
      featured: true,
    },
    {
      id: 2,
      title: "Instant follow-up emails",
      description: "Send perfectly drafted follow-up emails within seconds after every interview.",
      backgroundColor: "bg-white/10 backdrop-blur-xl",
      imagePlaceholder: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&h=400&fit=crop&q=80",
      featured: false,
    },
    {
      id: 3,
      title: "Who are you really interviewing?",
      description: "Learn everything about candidates before every call—where they work, what they do, and more.",
      backgroundColor: "bg-white/10 backdrop-blur-xl",
      imagePlaceholder: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=600&h=400&fit=crop&q=80",
      featured: false,
    },
    {
      id: 4,
      title: "Beautiful interview notes",
      description: "Instant shareable interview notes generated by AI.",
      backgroundColor: "bg-white/10 backdrop-blur-xl",
      imagePlaceholder: "https://images.unsplash.com/photo-1542744095-291d1f67b221?w=600&h=400&fit=crop&q=80",
      featured: false,
    },
  ];

  return (
    <section className="relative py-20 px-4 md:px-8 lg:px-16">
      <div className="max-w-7xl mx-auto">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white mb-4">
            Four ways we make your
            <br />
            interviews better
          </h2>
        </motion.div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 lg:gap-8">
          {features.map((feature, index) => (
            <motion.div
              key={feature.id}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              className={`
                ${feature.backgroundColor}
                rounded-3xl p-8 lg:p-10
                text-white
                hover:scale-[1.02] transition-transform duration-300
                border border-white/20
                shadow-2xl
              `}
            >
              {/* Image/Visual */}
              <div className="mb-6 rounded-2xl overflow-hidden bg-black/30 backdrop-blur-sm border border-white/10">
                <div className="relative w-full h-64 lg:h-80">
                  <Image
                    src={feature.imagePlaceholder}
                    alt={feature.title}
                    fill
                    className="object-cover opacity-70"
                  />
                </div>
              </div>

              {/* Content */}
              <div>
                <h3 className="text-2xl lg:text-3xl font-bold mb-3 text-white">
                  {feature.title}
                </h3>
                <p className="text-base lg:text-lg text-white/80">
                  {feature.description}
                </p>
              </div>

              {/* Optional: Add "Ask for Assist" button for featured card */}
              {feature.featured && (
                <div className="mt-6">
                  <button className="px-4 py-2 bg-white/20 hover:bg-white/30 rounded-lg text-sm font-medium backdrop-blur-sm transition-all text-white border border-white/20">
                    Ask AI for Assist
                  </button>
                </div>
              )}
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

