version: '3.8'
services:
  media-service:
    build: .
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - /Users/mukulgarg/Downloads/AIP backup/video_recordings:/app/uploads
